
plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

processResources {
    filteringCharset "UTF-8"
    inputs.property "mod_version", project.mod_version
    inputs.property "version", project.mod_version
    filesMatching("fabric.mod.json") {
        expand "version": project.mod_version, "mod_version": project.mod_version
    }
} 
version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}
repositories {
    mavenCentral()
    mavenLocal()
}
loom {}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = '11'
    targetCompatibility = '11'
    it.options.encoding = "UTF-8"
    it.options.release = 25
}

java {
    withSourcesJar()
}
jar {
    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId project.archives_base_name
            from components.java
        }
    }
    repositories {
    }
}

